name: Sync extensions, Lokalise and packages
on:
  push:
    branches:
      -master
  schedule:
    - cron: '*/20 * * * *'
jobs:
  sync:
    name: Read translations
    runs-on: php:7.3
    steps:
      - name: Composer install
        uses: MilesChou/composer-action@master
      - name: Read
        run: php trans lokalise:read
        env:
          LOKALISE_API_TOKEN: ${{ secrets.LOKALISE_API_TOKEN }}
      - name: Push
        run: php trans lokalise:push
        env:
          LOKALISE_API_TOKEN: ${{ secrets.LOKALISE_API_TOKEN }}
      - name: Commit
        uses: github-actions-x/commit@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: 'master'
          commit-message: 'publish latest translations'
          force-add: 'true'
          rebase: 'true'
      - name: Subsplit
        run: php trans subsplit

