name: Sync extensions, Lokalise and packages
on:
  push:
    branches:
      -master
  schedule:
    - cron: '*/30 * * * *'
jobs:
  sync:
    name: Sync translations
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: flarum-lang/sync-action@master
        env:
          LOKALISE_API_TOKEN: ${{ secrets.LOKALISE_API_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
